LBF.config({
    "deps": {
        "app.Collection": ["lang.isFunction", "lang.JSON", "app.REST", "util.Promise", "util.Tasks", "lib.Backbone", "lib.underscore", "app.RESTSync"],
        "app.Controller": ["lang.Core", "util.Attribute", "lib.jQuery", "lang.proxy", "lang.isFunction"],
        "app.Model": ["lang.isFunction", "lang.JSON", "app.REST", "util.Promise", "util.Tasks", "lib.Backbone", "lib.underscore", "app.RESTSync"],
        "app.REST": ["lang.extend", "lang.forEach", "lang.JSON", "lang.isFunction", "lib.jQuery", "util.Attribute", "util.Event", "util.Promise", "app.RESTPlugins.errorLog", "app.RESTPlugins.speedReport", "app.RESTPlugins.CSRFPatch"],
        "app.RESTPlugins.CSRFPatch": ["util.Cookie", "lang.JSON"],
        "app.RESTPlugins.errorLog": ["monitor.logger", "lang.extend"],
        "app.RESTPlugins.speedReport": ["lang.extend", "monitor.SpeedReport"],
        "app.RESTSync": ["lib.underscore"],
        "app.Router": ["lib.Backbone"],
        "app.View": ["lang.extend", "lib.jQuery", "lib.Backbone", "lib.underscore", "util.template"],
        "util.staticLocalStorage": ["util.localStorage", "lang.JSON", "lang.each"],
        "lang.Class": ["lang.toArray", "lang.extend"],
        "lang.Core": ["lang.extend"],
        "lang.extend": ["lang.isPlainObject"],
        "lang.Inject": ["lang.each"],
        "lang.isPlainObject": ["lang.isObject"],
        "lib.Backbone": ["lib.underscore", "lib.jQuery", "lang.JSON", "lib.underscore"],
        "lib.Highcharts": ["lib.jQuery"],
        "lib.jQuery": ["globalSettings", "util.Cookie"],
        "monitor.logger": ["lang.isObject", "lang.isString", "lang.toArray", "lang.JSON", "lang.extend", "lang.browser", "util.postReport"],
        "monitor.SpeedReport": ["util.report", "lang.Class", "util.serialize", "util.Attribute"],
        "ui.Nodes.Button": ["lang.browser", "ui.Nodes.Node"],
        "ui.Nodes.Checkbox": ["lang.proxy", "lang.browser", "ui.Nodes.Node", "{theme}/lbfUI/css/Checkbox.css"],
        "ui.Nodes.Node": ["lang.each", "util.defaults", "lang.proxy", "lang.Inject", "util.template", "util.Attribute", "lang.trim", "lang.isString", "lib.jQuery", "lang.Class"],
        "ui.Nodes.Popup": ["util.Style", "lib.jQuery", "lang.browser", "ui.Nodes.Node", "util.zIndexGenerator", "{theme}/lbfUI/css/Popup.css"],
        "ui.Nodes.Radio": ["lang.inArray", "lang.proxy", "lang.browser", "ui.Nodes.Node", "{theme}/lbfUI/css/Radio.css"],
        "ui.Nodes.Textarea": ["lang.browser", "ui.Nodes.Node"],
        "ui.Nodes.TextInput": ["lang.forEach", "lang.browser", "lang.isArray", "ui.Nodes.Node"],
        "ui.Nodes.Tip": ["lib.jQuery", "lang.extend", "util.zIndexGenerator", "ui.Nodes.Node", "ui.widget.Dropdown.Dropdown", "{theme}/lbfUI/css/Tip.css"],
        "ui.Plugins.Cursor": ["ui.Plugins.Plugin"],
        "ui.Plugins.Drag": ["util.Style", "ui.Plugins.Plugin", "util.zIndexGenerator", "{theme}/lbfUI/css/Drag.css"],
        "ui.Plugins.DragDrop": ["lang.extend", "ui.Plugins.Drag"],
        "ui.Plugins.Overlay": ["lang.proxy", "lang.Inject", "util.Style", "util.zIndexGenerator", "lib.jQuery", "ui.Plugins.Plugin"],
        "ui.Plugins.Pin": ["lib.jQuery", "ui.Plugins.Plugin", "util.zIndexGenerator"],
        "ui.Plugins.Plugin": ["lang.each", "lang.proxy", "ui.Nodes.Node"],
        "ui.widget.Autocomplete.Autocomplete": ["lang.extend", "ui.Nodes.TextInput", "ui.widget.Dropdown.Dropdown", "{theme}/lbfUI/css/Autocomplete.css"],
        "ui.widget.ComboBox.ComboBox": ["lib.jQuery", "lang.each", "lang.isArray", "lang.isFunction", "lang.isObject", "lang.isNumber", "lang.proxy", "util.template", "lang.extend", "util.zIndexGenerator", "ui.Nodes.Node", "ui.widget.Dropdown.Dropdown", "util.xssFilter"],
        "ui.widget.DatePicker.DatePicker": ["lang.proxy", "lang.forEach", "lang.isNumber", "lang.dateTool", "lang.extend", "util.contains", "ui.widget.Dropdown.Dropdown", "ui.widget.DatePicker.DatePickerTemplate", "{theme}/lbfUI/css/DatePicker.css"],
        "ui.widget.DatePicker.DatePickerRange": ["ui.widget.DatePicker.DatePicker", "lang.extend", "lang.proxy", "ui.Nodes.Popup", "lang.dateTool", "ui.widget.DatePicker.DatePickerRangeTemplate"],
        "ui.widget.Dropdown.Dropdown": ["lang.proxy", "util.template", "util.zIndexGenerator", "ui.Nodes.Popup", "{theme}/lbfUI/css/Dropdown.css"],
        "ui.widget.Editor.CountPlugin": ["lang.isFunction", "lang.proxy", "util.validates", "ui.Plugins.Plugin", "ui.Nodes.Popup"],
        "ui.widget.Editor.Editor": ["lang.extend", "ui.Nodes.Textarea", "ui.Plugins.Plugin", "ui.Plugins.Cursor", "{theme}/lbfUI/css/Editor.css"],
        "ui.widget.Editor.FacePlugin": ["ui.Plugins.Plugin", "ui.Nodes.Popup"],
        "ui.widget.Editor.ImagePlugin": ["lang.proxy", "util.Uploader", "ui.Plugins.Plugin", "ui.Nodes.Popup", "ui.widget.ImageViewer"],
        "ui.widget.Editor.LinkPlugin": ["lang.proxy", "util.validates", "ui.Plugins.Plugin", "ui.Nodes.TextInput", "ui.Nodes.Popup", "ui.Nodes.Button"],
        "ui.widget.FileUpload.FileUpload": ["lang.proxy", "lang.browser", "ui.Nodes.Node"],
        "ui.widget.FileUploader.ajaxUpload.ajaxUpload": ["lang.proxy", "ui.Nodes.Node", "ui.Nodes.Button", "lang.isFunction", "util.Cookie"],
        "ui.widget.FileUploader.FileUploader": ["lib.jQuery", "ui.Nodes.Node", "{theme}/lbfUI/css/FileUploader.css"],
        "ui.widget.FileUploader.iframeUpload.iframeUpload": ["lang.proxy", "lang.browser", "ui.Nodes.Node", "ui.Nodes.Button", "lang.isFunction", "util.Cookie", "lang.extend"],
        "ui.widget.FileUploader.swfUpload.init": ["lib.jQuery", "lang.proxy", "lang.extend", "ui.Nodes.Node", "ui.Nodes.Button", "lang.isFunction", "util.Cookie", "ui.widget.FileUploader.swfUpload.swfUploadQueue"],
        "ui.widget.FileUploader.swfUpload.swfUploadQueue": ["ui.widget.FileUploader.swfUpload.swfUpload"],
        "ui.widget.Gotop": ["lib.jQuery", "util.zIndexGenerator", "ui.Nodes.Node"],
        "ui.widget.Grid.Grid": ["ui.Nodes.Node", "lang.extend", "ui.widget.Pagination", "ui.Plugins.DragDrop", "ui.Plugins.Pin", "lang.isNumber", "lang.isArray", "{theme}/lbfUI/css/Grid.css"],
        "ui.widget.ICheckbox.ICheckbox": ["lib.jQuery", "ui.Nodes.Node", "lang.each", "lang.extend"],
        "ui.widget.ImageCrop.ImageCrop": ["ui.Nodes.Node", "lib.jQuery", "lang.isFunction", "ui.widget.Panel.ConfirmPanel", "lang.extend", "ui.widget.FileUploader.FileUploader", "util.imageLoader", "{theme}/lbfUI/css/ImageCrop.css", "ui.widget.ImageCrop.mouseWheel"],
        "ui.widget.ImageViewer": ["lang.proxy", "lang.browser", "ui.Nodes.Tip"],
        "ui.widget.IRadio.IRadio": ["lib.jQuery", "ui.Nodes.Node", "lang.each", "lang.extend"],
        "ui.widget.JScrollPane.JScrollPane": ["lib.jQuery", "util.mouseWheel", "{theme}/lbfUI/css/JScrollPane.css"],
        "ui.widget.LightTip.LightTip": ["lib.jQuery", "lang.extend", "ui.Nodes.Node", "ui.Nodes.Popup", "ui.Plugins.Overlay", "util.zIndexGenerator", "{theme}/lbfUI/css/LightTip.css"],
        "ui.widget.Menu.Menu": ["lang.proxy", "lang.extend", "lang.forEach", "lang.isArray", "util.template", "util.zIndexGenerator", "ui.widget.Dropdown.Dropdown", "{theme}/lbfUI/css/Menu.css"],
        "ui.widget.NumberSpinner.NumberSpinner": ["lang.isNumber", "lang.extend", "ui.Nodes.Node", "{theme}/lbfUI/css/NumberSpinner.css"],
        "ui.widget.Pagination": ["lang.isNumber", "lang.extend", "ui.Nodes.Node"],
        "ui.widget.Panel.AlertPanel": ["lang.extend", "ui.widget.Panel.Panel"],
        "ui.widget.Panel.ConfirmPanel": ["lang.extend", "ui.widget.Panel.Panel"],
        "ui.widget.Panel.Panel": ["lib.jQuery", "lang.forEach", "lang.proxy", "lang.extend", "util.zIndexGenerator", "util.Shortcuts", "ui.Nodes.Node", "ui.Nodes.Popup", "ui.Nodes.Button", "ui.Plugins.Drag", "ui.Plugins.Overlay", "{theme}/lbfUI/css/Panel.css"],
        "ui.widget.RichEditor.RichEditor": ["lang.browser", "lang.extend", "util.contains", "ui.Nodes.Node", "{theme}/lbfUI/css/RichEditor.css"],
        "ui.widget.Scrollspy.Scrollspy": ["lib.jQuery", "ui.Nodes.Node", "lang.extend", "{theme}/lbfUI/css/Scrollspy.css"],
        "ui.widget.Slider.Slider": ["ui.Nodes.Node", "ui.Plugins.DragDrop", "lang.extend"],
        "ui.widget.State.State": ["ui.Nodes.Node", "ui.Nodes.Popup", "lang.proxy", "lang.extend"],
        "ui.widget.Switchable.Slides": ["lang.extend", "lang.browser", "lang.inArray", "util.css3Detect", "ui.widget.Switchable.Switchable"],
        "ui.widget.Switchable.Switchable": ["lang.forEach", "lang.extend", "ui.Nodes.Node", "{theme}/lbfUI/css/Switchable.css"],
        "ui.widget.Switchable.TabView": ["lang.extend", "lang.forEach", "lang.browser", "lang.proxy", "ui.widget.Switchable.Switchable"],
        "ui.widget.TimePicker.TimePicker": ["lib.jQuery", "lang.extend", "ui.widget.Dropdown.Dropdown", "ui.widget.TimePicker.TimePickerTemplate", "{theme}/lbfUI/css/TimePicker.css"],
        "ui.widget.ZTree.ZTree": ["lib.jQuery", "{theme}/lbfUI/css/zTreeStyle.css"],
        "util.Attribute": ["lang.extend"],
        "util.Callbacks": ["lang.Class", "lang.forEach", "lang.extend", "lang.isFunction", "lang.isString", "lang.inArray"],
        "util.Event": ["lang.toArray", "util.Callbacks"],
        "util.eventProxy": ["lang.extend", "lib.Backbone"],
        "util.imageLoader": ["lang.browser"],
        "util.jsonp": ["util.request", "util.serialize"],
        "util.localStorage": ["util.Cookie", "lang.trim"],
        "util.moduleMemory": ["util.Tasks", "qidian.comp.REST", "util.template", "util.Promise", "util.GUID"],
        "util.Promise": ["lang.Class", "lang.forEach", "lang.extend", "lang.proxy", "lang.toArray", "lang.isFunction", "util.Callbacks"],
        "util.ptLoginHelper": ["util.RSA", "util.TEA", "util.md5"],
        "util.PubSub": ["lang.extend", "util.Event"],
        "util.Range": ["lang.Class", "lang.isString", "util.contains"],
        "util.region": ["lang.each", "util.regionData"],
        "util.requestAnimationFrame": ["lang.proxy"],
        "util.Selection": ["lang.Class", "util.Range"],
        "util.sessionStorage": ["util.localStorage", "util.Cookie", "util.domain"],
        "util.Style": ["lib.jQuery"],
        "util.Tasks": ["lang.proxy"],
        "util.Validform": ["{theme}/lbfUI/css/Validform.css", "ui.Nodes.Node", "lib.jQuery", "lang.extend", "lang.isFunction", "lang.isRegExp"]
    }
});